#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
lua2inc.py — 将 Lua 脚本目录转换为 C 头文件嵌入字符串

用法:
    python lua2inc.py <scripts_dir> <output_inc>

示例:
    python lua2inc.py applications/scripts applications/lua_script_table.inc

输出:
    lua_script_table.inc  — 包含脚本注册表，格式为:
        const lua_script_t lua_script_table[] = {
            {"led_blink",  "gpio_mode(28, 1)...\n"},
            {"sensor_read", "..."},
            {NULL, NULL}
        };
"""

import os
import sys
import glob


def escape_lua_string(text):
    """将 Lua 源码转义为 C 字符串，处理引号、反斜杠等特殊字符"""
    result = []
    for ch in text:
        if ch == '\\':
            result.append('\\\\')
        elif ch == '"':
            result.append('\\"')
        elif ch == '\n':
            result.append('\\n"\n"')
        elif ch == '\r':
            pass  # 忽略 Windows 换行符的 \r
        elif ch == '\t':
            result.append('\\t')
        else:
            result.append(ch)
    return ''.join(result)


def lua2inc(scripts_dir, output_inc):
    """将 scripts_dir 下所有 .lua 文件生成为一个 .inc 头文件"""

    # 收集所有 .lua 文件，按文件名排序确保顺序固定
    lua_files = sorted(glob.glob(os.path.join(scripts_dir, "*.lua")))

    if not lua_files:
        print(f"Warning: no .lua files found in '{scripts_dir}'")
        # 生成空表，避免编译报错
        with open(output_inc, 'w', encoding='utf-8') as f:
            f.write("/* Auto-generated by lua2inc.py - DO NOT EDIT */\n")
            f.write("#ifndef __LUA_SCRIPT_TABLE_INC__\n")
            f.write("#define __LUA_SCRIPT_TABLE_INC__\n\n")
            f.write("#include \"lua_script.h\"\n\n")
            f.write("const lua_script_t lua_script_table[] = {\n")
            f.write("    {NULL, NULL}\n")
            f.write("};\n\n")
            f.write("#endif /* __LUA_SCRIPT_TABLE_INC__ */\n")
        print(f"Generated empty table: {output_inc}")
        return

    with open(output_inc, 'w', encoding='utf-8') as f:
        f.write("/* Auto-generated by lua2inc.py - DO NOT EDIT */\n")
        f.write("/* Source files:\n")
        for lf in lua_files:
            f.write(f" *   {os.path.basename(lf)}\n")
        f.write(" */\n\n")
        f.write("#ifndef __LUA_SCRIPT_TABLE_INC__\n")
        f.write("#define __LUA_SCRIPT_TABLE_INC__\n\n")
        f.write("#include \"lua_script.h\"\n\n")

        # 生成脚本注册表
        f.write("const lua_script_t lua_script_table[] = {\n")

        max_name_len = 0
        entries = []
        for lf in lua_files:
            name = os.path.splitext(os.path.basename(lf))[0]
            max_name_len = max(max_name_len, len(name))

            with open(lf, 'r', encoding='utf-8') as sf:
                content = sf.read()

            escaped = escape_lua_string(content)
            # 去掉末尾多余的 "\n"\n""
            if escaped.endswith('\\n"\n"'):
                escaped = escaped[:-5]

            entries.append((name, escaped, os.path.getsize(lf)))

        for i, (name, escaped, size) in enumerate(entries):
            sep = '},'
            f.write(f'    {{"{name}",{" " * (max_name_len - len(name))} '
                    f'"{escaped}"{sep}  /* {size} bytes */\n')

        f.write("    {NULL, NULL}\n")
        f.write("};\n\n")

        # 生成脚本名称列表（用于 lua_list 命令）
        f.write("/* 脚本名称列表 */\n")
        f.write("static const char *lua_script_names[] = {\n")
        for name, _, _ in entries:
            f.write(f'    "{name}",\n')
        f.write("    NULL\n")
        f.write("};\n\n")

        f.write("#endif /* __LUA_SCRIPT_TABLE_INC__ */\n")

    print(f"Generated: {output_inc}")
    print(f"  Scripts: {len(entries)} file(s)")
    for name, _, size in entries:
        print(f"    {name:20s} {size:6d} bytes")


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)

    scripts_dir = sys.argv[1]
    output_inc = sys.argv[2]

    if not os.path.isdir(scripts_dir):
        print(f"Error: directory '{scripts_dir}' not found")
        sys.exit(1)

    lua2inc(scripts_dir, output_inc)


if __name__ == '__main__':
    main()